# Generated by Django 3.1.7 on 2021-06-07 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='first_name',
            field=models.CharField(default='first', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='last_name',
            field=models.CharField(default='name', max_length=200),
        ),
    ]
