# Generated by Django 3.1.7 on 2021-06-07 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0002_auto_20210606_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_name',
            field=models.CharField(max_length=200),
        ),
    ]
